version: "3"

services:     
  rbs:
    container_name: rbs
    build: server
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./server:/server
    ports:
      - "8000:8000"