version: "3"

services:     
  server:
    container_name: server
    build: server
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./server:/server
    ports:
      - "8000:8000"
  client:
    container_name: client
    build: client
    ports:
      - "4200:4200"
